# datasource
spring:
  datasource:
    url: jdbc:mysql:///health?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis  默认是不用配置， 前提是遵守Mapper代理的规则（6个）
mybatis:
  mapper-locations: classpath:com/itheima/mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.itheima.domain # 别名所在包
# config-location:  # 指定mybatis的核心配置文件
